---
- name: run if image is pulled
  command: /usr/local/bin/check_img calico

- name: check if image is pulled
  stat: path="/tmp/install/check_calico_img"
  register: check_calico_img

- name: pull calico from goodrain.me
  shell: "docker pull goodrain.me/{{ calico_image }}"
  when: check_calico_img.stat.isreg is not defined

- name: delete if nodename is existing
  file: path=/var/lib/calico/nodename state=absent

- name: Copy Network Role
  template:
    src: network.role.j2
    dest: "{{ node_role_dir }}/network.yaml"

- name: Copy calico conf
  template:
    src: cp-calico.conf.j2
    dest: /opt/rainbond/etc/cni/10-calico.conf
  when: inventory_hostname in groups['compute'] + groups['new-compute'] or inventory_hostname in groups['gateway'] + groups['new-gateway']

- name: Copy calico conf
  template:
    src: calico.conf.j2
    dest: /opt/rainbond/etc/cni/10-calico.conf
  when: inventory_hostname in groups['manage'] + groups['new-manage']

- name: Copy calicoctl binary from deploy
  copy:
    src: "{{ local_tools }}/bin/calicoctl"
    dest: "{{ bin_dir }}/calicoctl"
    mode: 0755

- name: Copy calicoctl cfg
  template:
    src: calicoctl.cfg.j2
    dest: /etc/calico/calicoctl.cfg

- name: Add Calico Health Check
  template:
    src: "network_{{ CLUSTER_NETWORK }}.sh.j2"
    dest: "{{ rbd_dir }}/health/network.sh"
    mode: 0777
  tags: health