---
- hosts: new-worker
  roles:
    - { role: rainvar, tags: default }
    - { role: prepare, tags: prepare }
    - { role: docker, tags: docker }
    - { role: kube-worker, tags: kube-worker }
    - { role: etcd-proxy, tags: etcd-proxy }
    - { role: health, tags: health }
    - { role: network_plugin/calico, when: "CLUSTER_NETWORK == 'calico'" }
    - { role: network_plugin/flannel, when: "CLUSTER_NETWORK == 'flannel'" }
    - { role: storage/nfs/client, when: "storage_type == 'nfs'" }
    - { role: node, tags: node }

- hosts: deploy
  roles:
    - { role: rainvar, tags: default }
    - { role: nodeup, tags: nodeup }