---
- hosts: all
  roles:
    - { role: rainvar, tags: default }
    - { role: bootstrap, tags: bootstrap }
    - { role: prepare, tags: prepare }

- hosts: manage[0]
  roles:
    - { role: rainvar, tags: default }
    - { role: storage/nfs/server, when: "storage_type == 'nfs'" }

- hosts: manage:new-compute:new-gateway
  roles:
    - { role: rainvar, tags: default }
    - { role: storage/nfs/client, when: "storage_type == 'nfs'" }
    - { role: storage/nas, when: "storage_type == 'nas'" }
    - { role: storage/gfs, when: "storage_type == 'gfs'" }

- hosts: manage:new-compute:new-gateway
  roles:
    - { role: rainvar, tags: default }
#    - { role: docker/install, tags: docker }

- hosts: manage
  roles:
    - { role: rainvar, tags: default }
    - { role: docker/image, tags: image }
    - { role: etcd/manage, tags: etcd }
    - { role: k8s/manage, tags: kube-master }

- hosts: new-compute
  roles:
    - { role: rainvar, tags: default }
#    - { role: k8s/compute, tags: kube-worker }
#    - { role: etcd/compute, tags: etcd-proxy }

- hosts: manage:new-compute:new-gateway
  roles:
  - { role: rainvar, tags: default }
#  - { role: network_plugin/calico, when: "CLUSTER_NETWORK == 'calico'" }
#  - { role: network_plugin/flannel, when: "CLUSTER_NETWORK == 'flannel'" }

- hosts: manage[0]
  roles:
    - { role: rainvar, tags: default }
    - { role: db, tags: db, when: "net_type == 'internal'" }

- hosts: new-gateway
  roles:
    - { role: rainvar, tags: default }
    - { role: gateway, tags: gateway }

- hosts: manage:new-compute
  roles:
    - { role: rainvar, tags: default }
    - { role: monitor, tags: monitor }
    - { role: node/core, tags: node }

- hosts: manage[0]
  roles:
    - { role: rainvar, tags: default }
    - { role: node/init, tags: nodeinit}
    - { role: node/up, tags: nodeup }
