---
- name: prepare rainbond
  file: name={{ item }} state=directory
  with_items:
    - "{{ bin_dir }}"
    - "{{ ca_dir }}"
    - /cache/build
    - /cache/source
    - "{{ rbd_dir }}/etc/rbd-api/region.goodrain.me/ssl"
    - "{{ rbd_dir }}/etc/kubernetes/ssl"
    - "{{ rbd_dir }}/etc/kubernetes/kubecfg"
    - "{{ rbd_dir }}/health"
    - "{{ rbd_dir }}/data"
    - "{{ rbd_dir }}/logs"
    - "{{ rbd_dir }}/envs"
    - "{{ rbd_dir }}/scripts/init"
    - "{{ rbd_dir }}/conf"
    - "{{ rbd_dir }}/etc/cni"
    - "{{ rbd_dir }}/bin"
    - "{{ rbd_dir }}/etc/node"
    - "{{ rbd_dir }}/.init"
    - "{{ rbd_dir }}/etc/tools"
    - "{{ rbd_dir }}/rainbond-ansible"
    - /root/.kube
    - /etc/docker
    - /root/.rbd
    - /grdata/services/ssh
    - /grdata/services/storage
    - /opt/rainbond/offline/images
    - /grdata/kubernetes
    - /etc/NetworkManager/conf.d
    - /etc/calico
    - /etc/docker/certs.d/goodrain.me
    - "{{ install_logs_dir }}"
  tags:
    - manage

- name: populate inventory into hosts file
  blockinfile:
    dest: /etc/hosts
    block: |-
      {% for item in (groups['manage'] + groups['compute'] + groups['etcd'] + groups['gateway'] + groups['new-manage'] + groups['new-compute'] + groups['new-gateway'] |default([]))|unique -%}
      {{hostvars[item]['ip']}} {{ item }}
      {% endfor %}
    state: present
    create: yes
    backup: yes
    marker: "# Ansible inventory hosts {mark}"

- name: localhost ipv4 in hosts file
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 localhost localhost.localdomain"
    regexp: '^127.0.0.1.*$'
    state: present
    backup: yes

- name: localhost ipv6 in hosts file
  lineinfile:
    dest: /etc/hosts
    line: "::1 localhost6 localhost6.localdomain"
    regexp: '^::1.*$'
    state: present
    backup: yes

- name: Copy Rainbond Tools
  copy: src={{ item }} dest={{ bin_dir }} owner=root mode=777
  with_fileglob:
    - "{{ base_dir }}/hack/files/bin/grtools/*"

- name: Create Rain User Group
  group:
    name: rain
    gid: 200
    system: yes
    state: present

- name: Create Rain User
  user:
    name: rain
    uid: 200
    shell: /sbin/nologin
    comment: "Rainbond user"
    create_home: yes
    groups: rain
    system: yes
    state: present

- name: Create remote_tmp for it is used by another module
  file:
    path: "{{ lookup('config', 'DEFAULT_REMOTE_TMP', on_missing='skip', wantlist=True) | first | default('~/.ansible/tmp') }}"
    state: directory
    mode: 0700

# add calico config 
- name: add NetworkManager 
  template: 
    src: calico.conf.j2 
    dest: /etc/NetworkManager/conf.d/calico.conf
  ignore_errors: True

- name: disable swap
  shell: "swapoff -a && sysctl -w vm.swappiness=0"
  ignore_errors: true

- name: disable swap from fstab 
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: 'yes'
  tags: prepare

- name: modprobe 
  modprobe: name={{ item }} state=present
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
#    - nf_conntrack_ipv4 # kernel < 4.19
#    - nf_conntrack  # kernel >= 4.19
  ignore_errors: true
  tags: prepare

- name: get kernel version
  set_fact:
     KERNEL_VER: "{{ ansible_kernel.split('-')[0].split('.')[0]|int + ansible_kernel.split('-')[0].split('.')[1]|int/100 }}"

- name: add nf_conntrack for kernel >= 4.19
  modprobe: name=nf_conntrack state=present
  when: "KERNEL_VER|float >= 4.19"
  ignore_errors: true

- name: add nf_conntrack_ipv4 for kernel < 4.19
  modprobe: name=nf_conntrack_ipv4 state=present
  when: "KERNEL_VER|float < 4.19"
  ignore_errors: true


#- name: add nf_conntrack for kernel 4.19
#  modprobe: name=nf_conntrack state=present
#  when: '"4.19" in ansible_kernel'
#  ignore_errors: true

- name: enable systemd modules
  service: name=systemd-modules-load enabled=yes

- name: enable k8s kernel modules 
  template: src=10-k8s-modules.conf.j2 dest=/etc/modules-load.d/10-k8s-modules.conf

- name:  update ulimits
  template: src=30-k8s-ulimits.conf.j2 dest=/etc/security/limits.d/30-k8s-ulimits.conf

- name:  update k8s.sysctl 
  template: src=95-k8s-sysctl.conf.j2 dest=/etc/sysctl.d/95-k8s-sysctl.conf

- name: sysctl -p 
  shell: "sysctl -p /etc/sysctl.d/95-k8s-sysctl.conf"
  ignore_errors: true

- name: Copy goodrain.me certificate
  copy:
    src: "{{ base_dir }}/hack/files/ssl/goodrain.me/server.crt"
    dest: /etc/docker/certs.d/goodrain.me/server.crt

- name: Copy grctl from deploy
  template:
    src: grctl.yaml.j2
    dest: /root/.rbd/grctl.yaml

- name: Copy Dns Config
  template:
    src: dns.role.j2
    dest: "{{ node_role_dir }}/dns.yaml"

- name: Copy Dns Health Check
  template:
    src: "{{ base_dir }}/hack/files/health/rbd-dns.sh"
    dest: "{{ rbd_dir }}/health/rbd-dns.sh"
    mode: 0777

- name: Copy local Dns Health Check
  template:
    src: local-dns.sh.j2
    dest: "{{ rbd_dir }}/health/local-dns.sh"
    mode: 0777

- name: Copy docker Health check
  template:
    src: "{{ base_dir }}/hack/files/health/check_docker.sh"
    dest: "{{ rbd_dir }}/health/check_docker.sh"
    mode: 0777

- name: Copy Health Only Health Role For Storage type nfs
  template:
    src: only_health.nfs.role.j2
    dest: "{{ node_role_dir }}/only_health.yaml"
  when: storage_type == "nfs"

- name: Copy Health Only Health Role FOr Other Storage type
  template:
    src: only_health.role.j2
    dest: "{{ node_role_dir }}/only_health.yaml"
  when: storage_type != "nfs"

- name: Copy Health Only Health Role For Only gateway
  template:
    src: only_health.role.j2
    dest: "{{ node_role_dir }}/only_health.yaml"
  when: noderule == "gateway" and storage_type == "nfs"

- name: Copy Health Role
  template:
    src: health.role.j2
    dest: "{{ node_role_dir }}/health.yaml"

- name: Copy Health Role For Only Gateway
  template:
    src: health.role.gateway.j2
    dest: "{{ node_role_dir }}/health.yaml"
  when: noderule == "gateway"

- name: Copy Storage Health Check
  template:
    src: "{{ base_dir }}/hack/files/health/storage.sh"
    dest: "{{ rbd_dir }}/health/storage.sh"
    mode: 0777

- name: Copy Add NFS Health Check
  template:
    src: "{{ base_dir }}/hack/files/health/check_nfs.sh"
    dest: "{{ rbd_dir }}/health/check_nfs.sh"
    mode: 0777
